## Playbook to install postgresql 9.6 from the offical postgres (pgdg) repo using `geerlingguy.postgresql` role
#
# Notes:
# - the role is expected to be in a configured role path (usually added via git submodule)
# - the target server host should not run selinux (in mode enforcing), as this might create issues
#
- hosts: all
  gather_facts: true
  become: yes
  vars:
#    postgresql_version: 9.6
#    postgresql_scl_version: 96
    postgresql_version: 10.5
    postgresql_scl_version: 10
    postgresql_use_scl: true
    postgresql_hba_entries_default:
      - { type: local, database: all, user: postgres, auth_method: peer }
      - { type: local, database: all, user: all, auth_method: peer }
      - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
      - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
    postgresql_hba_allow_all_ips_on_all_dbs: 
      - {type: host, database: all, user: all, address: "0.0.0.0/0", auth_method: md5}

  vars_prompt:
    - name: "postgresql_version"
      prompt: "Enter postgresql_version if not default"
      default: "10.5"
      private: no

    - name: "postgresql_scl_version"
      prompt: "Enter postgresql_scl_version if not default"
      default: "10"
      private: no

  pre_tasks:

    - name: check postgresql_version variable is set
      fail:
        msg: Variable {{ postgresql_version }} is not set
      when: postgresql_version is not defined

    - name: check postgresql_scl_version variable is set
      fail:
        msg: Variable {{ postgresql_scl_version }} is not set
      when: postgresql_scl_version is not defined

    # More infos on the "rh-postgresql96" SCL: https://www.softwarecollections.org/en/scls/rhscl/rh-postgresql96/
    # More infos on the "rh-postgresql10" SCL: https://www.softwarecollections.org/en/scls/rhscl/rh-postgresql10/

    - name: Enable RH SCL (Software Collections) on CentOS
      yum:
        name: centos-release-scl-rh
        state: present
      when: ansible_distribution == 'CentOS'

  roles:
    # Note: This requires the role contains the feature from PR: https://github.com/geerlingguy/ansible-role-postgresql/pull/96
    - name: ansible-role-postgresql
      # Note: It also works without explicilty enabling the repo
      #postgresql_enablerepo: "centos-sclo-rh"
#      postgresql_version: 9.6
#      postgresql_scl_version: 96
      postgresql_use_scl: true
      postgresql_data_dir: /var/opt/rh/rh-postgresql{{ postgresql_scl_version }}/lib/pgsql/data
      postgresql_bin_path: /opt/rh/rh-postgresql{{ postgresql_scl_version }}/root/usr/bin
      postgresql_config_path: /var/opt/rh/rh-postgresql{{ postgresql_scl_version }}/lib/pgsql/data
      postgresql_global_config_options:
        - option: listen_addresses
          value: "*"
        - option: max_connections
          value: "500" 
      postgresql_hba_entries: "{{ postgresql_hba_entries_default + postgresql_hba_allow_all_ips_on_all_dbs }}"
      ## Note: When install postgres on same node than ambari-server, to avoid pkg conflicts, disable 2 *syspaths packages:
      postgresql_packages:
      # - rh-postgresql96-postgresql-syspaths
      # - rh-postgresql96-postgresql-server-syspaths
        - rh-postgresql{{ postgresql_scl_version }}-postgresql
        - rh-postgresql{{ postgresql_scl_version }}-postgresql-server
        - rh-postgresql{{ postgresql_scl_version }}-postgresql-contrib-syspaths
        - rh-postgresql{{ postgresql_scl_version }}-postgresql-libs
      postgresql_daemon: rh-postgresql{{ postgresql_scl_version }}-postgresql

# this is required for 9.6
  tasks:
    - file:
        src: "/opt/rh/rh-postgresql{{ postgresql_scl_version }}/root/usr/lib64/libpq.so.rh-postgresql{{ postgresql_scl_version }}-5"
        dest: "{{ item }}/libpq.so.rh-postgresql{{ postgresql_scl_version }}-5"
        state: link
      loop:
        - /usr/lib64
        - /usr/lib
      when: ansible_distribution == 'CentOS'
