# from GitHub, overriding the name and specifying a specific tag
#- src: https://galaxy.ansible.com/geerlingguy/postgresql/
#- src: geerlingguy.postgresql
#- src: https://github.com/geerlingguy/ansible-role-postgresql
#  version: master
#  name: ansible-role-postgresql
