# from GitHub, overriding the name and specifying a specific tag
#- src: https://galaxy.ansible.com/geerlingguy/postgresql/
- src: geerlingguy.postgresql
  version: master
  name: ansible-role-postgresql
