---

- name: Create databases
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ item.value.name }}"
    state: present
    encoding: utf8
  with_dict: "{{ deployment.databases }}"

- name: Create database users
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ item.value.user }}"
    password: "{{ item.value.password }}"
    update_password: always
    priv: "{{ item.value.name }}.*:ALL"
    host: "%"
    state: present
  with_dict: "{{ deployment.databases }}"
