role_mappings:
  ACCUMULO16:
    - ACCUMULO16_GC
    - ACCUMULO16_MASTER
    - ACCUMULO16_MONITOR
    - ACCUMULO16_TRACER
    - ACCUMULO16_TSERVER
    - GARBAGE_COLLECTOR
    - GATEWAY
    - MONITOR
    - TRACER
  ACCUMULO_C6:
    - ACCUMULO_GC
    - ACCUMULO_LOGGER
    - ACCUMULO_MASTER
    - ACCUMULO_MONITOR
    - ACCUMULO_TRACER
    - ACCUMULO_TSERVER
    - GATEWAY
  ADLS_CONNECTOR:
  ATLAS:
    - ATLAS_SERVER
  AWS_S3:
  CORE_SETTINGS:
  DAS:
    - DAS_EVENT_PROCESSOR
    - DAS_WEBAPP
  DATA_CONTEXT_CONNECTOR:
  FLUME:
    - AGENT
  HBASE:
    - GATEWAY
    - HBASERESTSERVER
    - HBASETHRIFTSERVER
    - MASTER
    - REGIONSERVER
  HDFS:
    - BALANCER
    - DATANODE
    - FAILOVERCONTROLLER
    - GATEWAY
    - HTTPFS
    - JOURNALNODE
    - NAMENODE
    - NFSGATEWAY
    - SECONDARYNAMENODE
  HIVE:
    - GATEWAY
    - HIVEMETASTORE
    - HIVESERVER2
    - WEBHCAT
  HIVE_EXEC:
  HIVE_LLAP:
    - LLAPPROXY
  HIVE_ON_TEZ:
  HUE:
    - HUE_LOAD_BALANCER
    - HUE_SERVER
    - KT_RENEWER
  IMPALA:
    - CATALOGSERVER
    - IMPALAD
    - STATESTORE
  ISILON:
    - GATEWAY
  KMS:
    - KMS
  KAFKA:
    - GATEWAY
    - KAFKA_BROKER
    - KAFKA_MIRROR_MAKER
  KEYTRUSTEE:
    - KMS_KEYTRUSTEE
  KEYTRUSTEE_SERVER:
    - DB_ACTIVE
    - DB_PASSIVE
    - KEYTRUSTEE_ACTIVE_SERVER
    - KEYTRUSTEE_PASSIVE_SERVER
  KNOX:
    - IDBROKER
    - KNOX_GATEWAY
  KS_INDEXER:
    - HBASE_INDEXER
  KUDU:
    - KUDU_MASTER
    - KUDU_TSERVER
  LIVY:
    - GATEWAY
    - LIVY_SERVER
  LUNA_KMS:
    - HSMKP_LUNA
    - HSMKP_METASTORE_LUNA
  MAPREDUCE:
    - FAILOVERCONTROLLER
    - GATEWAY
    - JOBTRACKER
    - TASKTRACKER
  OOZIE:
    - OOZIE_SERVER
  OZONE:
    - GATEWAY
    - OZONE_DATANODE
    - OZONE_MANAGER
    - OZONE_RECON
    - S3_GATEWAY
    - STORAGE_CONTAINER_MANAGER
  PHOENIX:
    - PHOENIX_QUERY_SERVER
  RANGER:
    - RANGER_ADMIN
    - RANGER_TAGSYNC
    - RANGER_USERSYNC
  SENTRY:
    - SENTRY_SERVER
  SOLR:
    - GATEWAY
    - SOLR_SERVER
  SPARK_ON_YARN:
    - GATEWAY
    - SPARK_YARN_HISTORY_SERVER
  SPARK:
    - GATEWAY
    - SPARK_HISTORY_SERVER
    - SPARK_MASTER
    - SPARK_WORKER
  SPARK2_ON_YARN:
    - GATEWAY
    - SPARK2_YARN_HISTORY_SERVER
  SQOOP_CLIENT:
    - GATEWAY
  SQOOP:
    - SQOOP_SERVER
  TEZ:
    - GATEWAY
  THALES_KMS:
    - HSMKP_METASTORE_THALES
    - HSMKP_THALES
  YARN:
    - GATEWAY
    - JOBHISTORY
    - NODEMANAGER
    - RESOURCEMANAGER
  ZEPPELIN:
    - ZEPPELIN_SERVER
  ZOOKEEPER:
    - SERVER
